import { type NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { headers } from "next/headers";

const resend = new Resend(process.env.NEXT_PUBLIC_RESEND_API_KEY || "re_dummy");

// Internal API key for server-to-server calls
const INTERNAL_API_KEY = process.env.INTERNAL_API_KEY || "internal-protection-key";

interface SuspiciousActivityPayload {
  userId: string;
  lessonPath: string;
  reason: string;
  metadata?: Record<string, unknown>;
  timestamp: string;
}

export async function POST(request: NextRequest) {
  try {
    // Verify internal API key to prevent external abuse
    const headersList = await headers();
    const apiKey = headersList.get("x-internal-api-key");
    
    if (apiKey !== INTERNAL_API_KEY) {
      return NextResponse.json({ error: "Unauthorised" }, { status: 401 });
    }

    const payload: SuspiciousActivityPayload = await request.json();
    const { userId, lessonPath, reason, metadata, timestamp } = payload;

    // Format metadata for email
    const metadataText = metadata 
      ? Object.entries(metadata)
          .map(([key, value]) => `  • ${key}: ${value}`)
          .join("\n")
      : "No additional metadata";

    const emailText = `
⚠️ Suspicious Activity Detected

User ID: ${userId}
Lesson: ${lessonPath}
Reason: ${reason}
Time: ${timestamp}

Additional Details:
${metadataText}

---
This alert was generated by the course content protection system.
Review this user's activity in the admin dashboard.
    `.trim();

    const data = await resend.emails.send({
      from: "d×e Alerts <hello@designengineer.xyz>",
      to: ["hello@designengineer.xyz"],
      subject: `⚠️ Suspicious Course Activity: ${reason}`,
      text: emailText,
    });

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error("Failed to send suspicious activity email:", error);
    return NextResponse.json(
      { error: "Failed to send alert" }, 
      { status: 500 }
    );
  }
}
